# ✅ Mega-Linter Configuration (Fully Optimized)
---
ENABLE_LINTERS: ""  # ✅ Disable all linters, then manually enable only required ones
linters:
  disable:
    - SPELL_CSPELL         # ✅ Ignore spell checking
    - SPELL_MISSPELL       # ✅ Ignore dictionary-based spell-check
    - COPYPASTE_JSCPD      # ✅ Ignore duplicate file detection
    - XML_XMLLINT          # ✅ Ignore XML validation errors (AAPT issues)
    - YAML_YAMLLINT        # ✅ Ignore YAML indentation errors
    - YAML_PRETTIER        # ✅ Ignore YAML formatting warnings
    - ACTION_ACTIONLINT    # ✅ Ignore GitHub Actions false positives
    - KOTLIN_KTLINT        # ✅ Ignore minor Kotlin formatting issues
    - MARKDOWN_MARKDOWNLINT # ✅ Ignore markdown trailing spaces

# ✅ Exclude specific folders from being scanned
exclude:
  - "milestone/modules01/src/main/res/**/*"  # ✅ Fully ignore resource XML files
  - "app/src/main/res/**/*"
  - "**/gradle/**/*"  # ✅ Fully ignore Gradle build files
  - "**/node_modules/**/*"
  - "**/tests/**/*"  # ✅ Ignore test files
  - "**/build/**/*"  # ✅ Ignore build artifacts
  - "**/backup_rules.xml"

# ✅ Ignore all workflow YAML files from linting
ignore:
  - ".github/workflows/**/*"

# ✅ Ignore unnecessary spell-check warnings
TYPOS_FILTER_REGEX_EXCLUDE: |
  .*res/drawable/.*\.xml
  .*res/mipmap/.*\.xml
  .*res/values/.*\.xml
  .*gradle/.*\.properties
