# ✅ Optimized MegaLinter Configuration File
---
# ✅ Enable all linters
ENABLED_LINTERS:
  - ALL

# ✅ Use a custom spell-check dictionary
SPELL_CSPELL_CONFIG_FILE: ".cspell.json"

# ✅ Ensure .mega-linter-ignore is used
MEGA_LINTER_IGNORE_FILE: ".mega-linter-ignore"

# ✅ Ignore files listed in .gitignore
IGNORE_GITIGNORED_FILES: true

# ✅ Exclude unnecessary directories to optimize linting
EXCLUDED_DIRECTORIES:
  - app/src/androidTest
  - app/src/test
  - milestone/modules01/src/androidTest
  - milestone/modules01/src/test

# ✅ Exclude unnecessary files
EXCLUDED_FILES:
  - "**/*.lock"
  - "**/*.log"
  - "**/*.min.js"
  - "**/*.bundle.js"
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/.gradle/**"
  - "**/.idea/**"
  - "**/.vscode/**"
  - "**/coverage/**"
  - "**/reports/**"
  - "**/test-results/**"
  - "**/build/**"
  - "**/dist/**"

# ✅ Reduce log spam but keep useful information
LOG_LEVEL: INFO  # Use INFO instead of DEBUG for cleaner logs

# ✅ Fail pipeline if genuine errors are found
DISABLE_ERRORS: false
FAIL_IF_ERROR: true  # Ensures pipeline fails if errors exist

# ✅ Run linters in parallel to improve performance
PARALLEL: true

# ✅ Auto-fix issues where possible
APPLY_FIXES: all
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: commit

# ✅ Security: Protect sensitive environment variables
SECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
  - PAT
  - OX_API_KEY
  - MY_SECRET_TOKEN

# ✅ Exclude test folders from linting (GitHub Actions-specific)
FILTER_REGEX_EXCLUDE: ".*(test|androidTest).*"

# ✅ Report output directory (can be disabled if not needed)
REPORT_OUTPUT_FOLDER: "${GITHUB_WORKSPACE}/megalinter-reports"

# ✅ Other useful optimizations
CLEAR_REPORT_FOLDER: true  # Clean report folder before each run
PRINT_ALL_FILES: false  # Do not print all files, only count them
SHOW_SKIPPED_LINTERS: false  # Hide skipped linters to reduce log clutter
