# MegaLinter Configuration File
---
# ✅ Enable all linters
ENABLED_LINTERS:
  - ALL

# ✅ Use a custom spell-check dictionary
SPELL_CSPELL_CONFIG_FILE: ".cspell.json"

# ✅ Ensure .mega-linter-ignore is used
MEGA_LINTER_IGNORE_FILE: ".mega-linter-ignore"

# ✅ Automatically exclude all files from .gitignore
GIT_FILTER_REPO: true  # ✅ Exclude all ignored files from linting

# ✅ Exclude common test & generated directories
EXCLUDED_DIRECTORIES:
  - app/src/androidTest
  - app/src/test
  - milestone/modules01/src/androidTest/
  - milestone/modules01/src/test/

# ✅ Exclude unnecessary files
EXCLUDED_FILES:
  - "**/*.lock"
  - "**/*.log"
  - "**/*.min.js"
  - "**/*.bundle.js"
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/.gradle/**"
  - "**/.idea/**"
  - "**/.vscode/**"
  - "**/coverage/**"
  - "**/reports/**"
  - "**/test-results/**"
  - "**/build/**"
  - "**/dist/**"

# ✅ Set logging level to DEBUG for troubleshooting
LOG_LEVEL: DEBUG

# ✅ Fail the pipeline if errors are found
DISABLE_ERRORS: false
