# ✅ Optimized MegaLinter Configuration File
---
# ✅ Enable all linters
ENABLED_LINTERS:
  - ALL

DISABLED_LINTERS:
  - ACTION
  - BASH
  - SHELL

# ✅ Use a custom spell-check dictionary
SPELL_CSPELL_CONFIG_FILE: "config/.cspell.json"

# ✅ Load Custom `jscpd` Configuration File
JSCPD_CONFIG_FILE: "config/.jscpd.json"

# ✅ Allow up to 15% code duplication (if not using `.jscpd.json`)
JSCPD_ARGS: "--threshold 15"

# ✅ Ensure .mega-linter-ignore is used
MEGA_LINTER_IGNORE_FILE: "config/.mega-linter-ignore"

# ✅ Ignore files listed in .gitignore
IGNORE_GITIGNORED_FILES: true

# ✅ If using Kotlin, load detekt configuration
KOTLIN_DETEKT_CONFIG_FILE: "config/.detekt.yml"

EXCLUDED_DIRECTORIES:
  - "config/"   # ✅ Exclude configuration folder
  - "reports/"  # ✅ Exclude reports folder
  - "app/src/androidTest/"
  - "app/src/test/"
  - "milestone/modules01/src/androidTest/"
  - "milestone/modules01/src/test/"
  - ".github/workflows/"
  - ".gradle/"
  - "gradle/"
  - "gradle/wrapper/"
  - "gradlew/"  # ✅ Exclude Gradle wrapper script directory
  - "build/"
  - ".idea/"
  - ".vscode/"
  - "docs/"

EXCLUDED_FILES:
  - "config/**"   # ✅ Exclude configuration files
  - "reports/**"  # ✅ Exclude reports directory
  - "gradlew"  # ✅ Exclude Gradle wrapper script (Linux/Mac)
  - "gradlew.bat"  # ✅ Exclude Gradle wrapper script (Windows)
  - "**/app/src/androidTest/**"
  - "**/app/src/test/**"
  - "**/milestone/modules01/src/androidTest/**"
  - "**/milestone/modules01/src/test/**"
  - "**/.github/workflows/**"
  - "**/.gradle/**"
  - "**/gradle/**"
  - "**/gradle/wrapper/**"
  - "**/build/**"
  - "**/.idea/**"
  - "**/.vscode/**"
  - "**/docs/**"
  - "**/README.md"

# ✅ Reduce log spam but keep useful information
LOG_LEVEL: INFO  # Use INFO instead of DEBUG for cleaner logs

# ✅ Fail pipeline if genuine errors are found
DISABLE_ERRORS: false
FAIL_IF_ERROR: true  # Ensures pipeline fails if errors exist

# ✅ Run linters in parallel to improve performance
PARALLEL: true

# ✅ Auto-fix issues where possible
APPLY_FIXES: all
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: commit

# ✅ Security: Protect sensitive environment variables
SECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
  - PAT
  - OX_API_KEY
  - MY_SECRET_TOKEN

# ✅ Exclude test folders from linting (GitHub Actions-specific)
FILTER_REGEX_EXCLUDE: ".*(test|androidTest).*"

# ✅ Report output directory (updated)
REPORT_OUTPUT_FOLDER: "${GITHUB_WORKSPACE}/reports/megalinter-reports"

# ✅ Other useful optimizations
CLEAR_REPORT_FOLDER: true  # Clean report folder before each run
PRINT_ALL_FILES: false  # Do not print all files, only count them
SHOW_SKIPPED_LINTERS: false  # Hide skipped linters to reduce log clutter